NEWCHARMAP charmap0
; 40:4000
	charmap " ", $00
	charmap "死", $01
	charmap "之", $02
	charmap "吻", $03
	charmap "狂", $04
	charmap "咬", $05
	charmap "打", $06
	charmap "擊", $07
	charmap "瘋", $08
	charmap "突", $09
	charmap "防", $0a
	charmap "禦", $0b
	charmap "破", $0c
	charmap "碎", $0d
	charmap "催", $0e
	charmap "眠", $0f
	charmap "術", $10
	charmap "煙", $11
	charmap "幕", $12
	charmap "彈", $13
	charmap "百", $14
	charmap "裂", $15
	charmap "巴", $16
	charmap "掌", $17
	charmap "全", $18
	charmap "力", $19
	charmap "一", $1a
	charmap "集", $1b
	charmap "氣", $1c
	charmap "硬", $1d
	charmap "化", $1e
	charmap "封", $1f
	charmap "印", $20
	charmap "忍", $21
	charmap "耐", $22
	charmap "人", $23
	charmap "攻", $24
	charmap "綑", $25
	charmap "綁", $26
	charmap "精", $27
	charmap "神", $28
	charmap "中", $29
	charmap "療", $2a
	charmap "傷", $2b
	charmap "尖", $2c
	charmap "叫", $2d
	charmap "犧", $2e
	charmap "牲", $2f
	charmap "勒", $30
	charmap "緊", $31
	charmap "不", $32
	charmap "放", $33
	charmap "電", $34
	charmap "光", $35
	charmap "閃", $36
	charmap "分", $37
	charmap "身", $38
	charmap "熱", $39
	charmap "血", $3a
	charmap "正", $3b
	charmap "拳", $3c
	charmap "石", $3d
	charmap "縮", $3e
	charmap "小", $3f
	charmap "槍", $40
	charmap "刺", $41
	charmap "洗", $42
	charmap "腦", $43
	charmap "拍", $44
	charmap "翅", $45
	charmap "膀", $46
	charmap "偷", $47
	charmap "吃", $48
	charmap "步", $49
	charmap "先", $4a
	charmap "發", $4b
	charmap "制", $4c
	charmap "角", $4d
	charmap "致", $4e
	charmap "命", $4f
	charmap "殺", $50
	charmap "狼", $51
	charmap "嚎", $52
	charmap "潛", $53
	charmap "哀", $54
	charmap "號", $55
	charmap "沉", $56 ; ?
	charmap "睡", $57
	charmap "疾", $58
	charmap "風", $59
	charmap "護", $5a
	charmap "銅", $5b
	charmap "牆", $5c
	charmap "鐵", $5d
	charmap "壁", $5e
	charmap "瞄", $5f
	charmap "準", $60
	charmap "劍", $61
	charmap "切", $62
	charmap "斬", $63
	charmap "撞", $64
	charmap "刀", $65
	charmap "兩", $66
	charmap "斷", $67
	charmap "靈", $68
	charmap "二", $69
	charmap "流", $6a
	charmap "盾", $6b
	charmap "勢", $6c
	charmap "瞬", $6d
	charmap "間", $6e
	charmap "手", $6f
	charmap "居", $70
	charmap "合", $71
	charmap "蓄", $72
	charmap "鬥", $73
	charmap "‧", $74 ; hyphenation point (more squished)
	charmap "嵐", $75
	charmap "無", $76
	charmap "雙", $77
	charmap "噸", $78
	charmap "摔", $79
	charmap "地", $7a
	charmap "獄", $7b
	charmap "車", $7c
	charmap "必", $7d
	charmap "投", $7e
	charmap "擲", $7f
	charmap "天", $80
	charmap "寒", $81
	charmap "冰", $82
	charmap "烈", $83
	charmap "焰", $84
	charmap "吸", $85
	charmap "收", $86
	charmap "反", $87
	charmap "亂", $88 ; ?
	charmap "通", $89
	charmap "火", $8a
	charmap "炎", $8b
	charmap "噴", $8c
	charmap "射", $8d
	charmap "旋", $8e
	charmap "爆", $8f
	charmap "炸", $90
	charmap "鳥", $91
	charmap "翼", $92
	charmap "同", $93
	charmap "歸", $94
	charmap "於", $95
	charmap "盡", $96
	charmap "毒", $97
	charmap "濃", $98
	charmap "泡", $99
	charmap "沫", $9a
	charmap "雨", $9b
	charmap "飄", $9c
	charmap "紅", $9d
	charmap "強", $9e
	charmap "水", $9f
	charmap "柱", $a0
	charmap "暴", $a1
	charmap "海", $a2
	charmap "嘯", $a3
	charmap "凍", $a4
	charmap "束", $a5
	charmap "雪", $a6
	charmap "黑", $a7
	charmap "暗", $a8
	charmap "飛", $a9
	charmap "砂", $aa
	charmap "走", $ab
	charmap "落", $ac
	charmap "崩", $ad
	charmap "挖", $ae
	charmap "洞", $af
	charmap "大", $b0
	charmap "震", $b1
	charmap "殞", $b2
	charmap "巨", $b3
	charmap "雷", $b4
	charmap "闇", $b5
	charmap "殛", $b6
	charmap "頂", $b7
	charmap "磁", $b8
	charmap "波", $b9
	charmap "星", $ba
	charmap "法", $bb
	charmap "藤", $bc
	charmap "鞭", $bd
	charmap "樹", $be
	charmap "汁", $bf ; ?
	charmap "散", $c0
	charmap "葉", $c1
	charmap "片", $c2
	charmap "太", $c3
	charmap "陽", $c4
	charmap "花", $c5
	charmap "寄", $c6
	charmap "魂", $c7
	charmap "種", $c8
	charmap "子", $c9
	charmap "香", $ca
	charmap "甜", $cb
	charmap "孢", $cc
	charmap "麻", $cd ; ?
	charmap "痺", $ce
	charmap "粉", $cf
	charmap "猛", $d0
	charmap "舌", $d1
	charmap "頭", $d2
	charmap "舔", $d3
	charmap "怨", $d4
	charmap "恨", $d5
	charmap "衝", $d6
	charmap "邪", $d7
	charmap "惡", $d8
	charmap "侵", $d9
	charmap "蝕", $da
	charmap "纒", $db ; ?
	charmap "音", $dc
	charmap "魅", $dd
	charmap "惑", $de
	charmap "干", $df

NEWCHARMAP charmap1
; 40:6000
	charmap "擾", $00
	charmap "詛", $01
	charmap "咒", $02
	charmap "真", $03
	charmap "空", $04 ; ?
	charmap "渦", $05
	charmap "龍", $06
	charmap "捲", $07 ; ?
	charmap "沙", $08
	charmap "漠", $09
	charmap "燕", $0a
	charmap "舞", $0b
	charmap "替", $0c
	charmap "弓", $0d
	charmap "忽", $0e ; ?
	charmap "怒", $0f
	charmap "國", $10
	charmap "黏", $11
	charmap "液", $12
	charmap "模", $13
	charmap "仿", $14
	charmap "霧", $15 ; ?
	charmap "瓦", $16
	charmap "斯", $17
	charmap "淬", $18
	charmap "回", $19
	charmap "復", $1a
	charmap "獸", $1b
	charmap "竊", $1c
	charmap "變", $1d
	charmap "遁", $1e ; ?
	charmap "鏡", $1f
	charmap "謎", $20
	charmap "浴", $21
	charmap "重", $22
	charmap "生", $23
	charmap "華", $24
	charmap "三", $25
	charmap "昧", $26
	charmap "障", $27
	charmap "主", $28
	charmap "怪", $29
	charmap "1", $2a
	charmap "2", $2b
	charmap "道", $2c ; ?
	charmap "具", $2d
	charmap "交", $2e
	charmap "換", $2f
	charmap "逃", $30
	charmap "跑", $31
	charmap "嗯", $32
	charmap "，", $33
	charmap "找", $34
	charmap "!", $35
	charmap "伴", $36
	charmap "圖", $37
	charmap "鑑", $38
	charmap "存", $39
	charmap "檔", $3a
	charmap "移", $3b
	charmap "位", $3c
	charmap "詳", $3d
	charmap "細", $3e
	charmap "使", $3f
	charmap "用", $40
	charmap "丟", $41
	charmap "棄", $42
	charmap "是", $43
	charmap "否", $44
	charmap "裝", $45
	charmap "備", $46
	charmap "確", $47
	charmap "定", $48
	charmap "取", $49
	charmap "消", $4a
	charmap "木", $4b
	charmap "格", $4c
	charmap "般", $4d
	charmap "請", $4e
	charmap "選", $4f
	charmap "擇", $50
	charmap "的", $51
	charmap "類", $52
	charmap "。", $53
	charmap "技", $54
	charmap "巧", $55
	charmap "已", $56
	charmap "滿", $57
	charmap "要", $58
	charmap "忘", $59
	charmap "記", $5a
	charmap "舊", $5b ; ?
	charmap "嗎", $5c
	charmap "?", $5d
	charmap "哪", $5e
	charmap "項", $5f
	charmap "學", $60
	charmap "習", $61
	charmap "到", $62
	charmap "新", $63
	charmap "了", $64
	charmap "有", $65
	charmap "案", $66
	charmap "錄", $67
	charmap "覆", $68
	charmap "蓋", $69
	charmap "成", $6a
	charmap "功", $6b
	charmap "失", $6c
	charmap "敗", $6d
	charmap "土", $6e
	charmap "草", $6f
	charmap "速", $70
	charmap "度", $71
	charmap "魔", $72
	charmap "經", $73
	charmap "驗", $74
	charmap "值", $75
	charmap "膠", $76
	charmap "囊", $77
	charmap "極", $78
	charmap "品", $79
	charmap "利", $7a
	charmap "果", $7b
	charmap "實", $7c
	charmap "醫", $7d
	charmap "包", $7e
	charmap "效", $7f
	charmap "蔡", $80
	charmap "超", $81
	charmap "健", $82
	charmap "康", $83
	charmap "針", $84
	charmap "劑", $85
	charmap "解", $86
	charmap "清", $87
	charmap "興", $88
	charmap "奮", $89
	charmap "除", $8a
	charmap "膏", $8b
	charmap "萬", $8c
	charmap "能", $8d
	charmap "急", $8e
	charmap "救", $8f
	charmap "機", $90
	charmap "器", $91
	charmap "甦", $92
	charmap "儀", $93
	charmap "壽", $94
	charmap "司", $95
	charmap "源", $96
	charmap "補", $97
	charmap "充", $98
	charmap "營", $99
	charmap "養", $9a
	charmap "餐", $9b
	charmap "迴", $9c
	charmap "避", $9d
	charmap "高", $9e
	charmap "軟", $9f
	charmap "呆", $a0
	charmap "滞", $a1
	charmap "眼", $a2
	charmap "遲", $a3
	charmap "緩", $a4
	charmap "隱", $a5 ; ?
	charmap "設", $a6
	charmap "達", $a7
	charmap "奇", $a8
	charmap "線", $a9
	charmap "晶", $aa
	charmap "3", $ab
	charmap "4", $ac
	charmap "5", $ad
	charmap "6", $ae
	charmap "7", $af
	charmap "8", $b0
	charmap "9", $b1
	charmap "0", $b2
	charmap "蹟", $b3
	charmap "元", $b4
	charmap "點", $b5
	charmap "滴", $b6
	charmap "魚", $b7
	charmap "螫", $b8 ; ?
	charmap "螫", $b9 ; ?
	charmap "娘", $ba
	charmap "鱗", $bb
	charmap "淚", $bc
	charmap "淚", $bd
	charmap "甲", $be
	charmap "羽", $bf
	charmap "衣", $c0
	charmap "鬧", $c1
	charmap "鐘", $c2
	charmap "守", $c3
	charmap "玉", $c4
	charmap "幻", $c5
	charmap "特", $c6
	charmap "殊", $c7
	charmap "可", $c8
	charmap "服", $c9
	charmap "科", $ca
	charmap "以", $cb
	charmap "很", $cc
	charmap "率", $cd
	charmap "體", $ce
	charmap "方", $cf
	charmap "便", $d0
	charmap "隨", $d1
	charmap "而", $d2
	charmap "所", $d3
	charmap "提", $d4
	charmap "煉", $d5
	charmap "％", $d6
	charmap "內", $d7
	charmap "含", $d8
	charmap "傳", $d9
	charmap "說", $da
	charmap "狀", $db
	charmap "態", $dc
	charmap "燒", $dd
	charmap "涷", $de
	charmap "活", $df

NEWCHARMAP charmap2
; 41:4000
	charmap "並", $00
	charmap "單", $01
	charmap "數", $02
	charmap "戰", $03
	charmap "昇", $04
	charmap "降", $05
	charmap "低", $06
	charmap "對", $07
	charmap "從", $08
	charmap "脫", $09
	charmap "出", $0a
	charmap "開", $0b
	charmap "敵", $0c
	charmap "物", $0d
	charmap "偵", $0e
	charmap "測", $0f
	charmap "置", $10
	charmap "絕", $11
	charmap "相", $12
	charmap "當", $13
	charmap "苦", $14
	charmap "澀", $15
	charmap "等", $16
	charmap "級", $17
	charmap "離", $18
	charmap "迷", $19
	charmap "宮", $1a
	charmap "載", $1b
	charmap "著", $1c
	charmap "祕", $1d
	charmap "密", $1e
	charmap "~", $1f
	charmap "沈", $20
	charmap "後", $21
	charmap "即", $22
	charmap "亡", $23
	charmap "也", $24
	charmap "似", $25
	charmap "蘊", $26
	charmap "藏", $27
	charmap "还", $28 ; ?
	charmap "漸", $29
	charmap "增", $2a ; ?
	charmap "加", $2b
	charmap "屬", $2c
	charmap "性", $2d
	charmap "威", $2e
	charmap "陷", $2f
	charmap "入", $30
	charmap "深", $31
	charmap "時", $32
	charmap "會", $33
	charmap "噪", $34
	charmap "吵", $35
	charmap "醒", $36
	charmap "擁", $37
	charmap "者", $38
	charmap "帶", $39
	charmap "諸", $3a
	charmap "符", $3b
	charmap "止", $3c
	charmap "任", $3d
	charmap "何", $3e
	charmap "異", $3f
	charmap "常", $40
	charmap "夢", $41
	charmap "聖", $42
	charmap "潔", $43
	charmap "量", $44
	charmap "此", $45
	charmap "處", $46
	charmap "原", $47
	charmap "那", $48
	charmap "完", $49
	charmap "你", $4a
	charmap "錢", $4b
	charmap "夠", $4c
	charmap "買", $4d
	charmap "幾", $4e
	charmap "個", $4f
	charmap "呢", $50
	charmap "賣", $51
	charmap "務", $52
	charmap "目", $53
	charmap "欲", $54
	charmap "查", $55
	charmap "看", $56
	charmap "這", $57
	charmap "隻", $58
	charmap "抱", $59
	charmap "歉", $5a
	charmap "領", $5b
	charmap "隊", $5c
	charmap "伍", $5d
	charmap "更", $5e
	charmap "釋", $5f
	charmap "被", $60
	charmap "基", $61
	charmap "本", $62
	charmap "比", $63
	charmap "安", $64
	charmap "還", $65
	charmap "%", $66
	charmap "且", $67
	charmap "部", $68
	charmap "非", $69
	charmap "遇", $6a
	charmap "自", $6b
	charmap "己", $6c
	charmap "弱", $6d
	charmap "碰", $6e
	charmap "釣", $6f
	charmap "餌", $70
	charmap "感", $71
	charmap "應", $72
	charmap "寶", $73
	charmap "槌", $74
	charmap "獅", $75
	charmap "吼", $76
	charmap "蠻", $77 ; ?
	charmap "鑽", $78
	charmap "孔", $79
	charmap "剝", $7a
	charmap "奪", $7b
	charmap "冷", $7c
	charmap "球", $7d
	charmap "刃", $7e
	charmap "茅", $7f
	charmap "核", $80
	charmap "呼", $81
	charmap "喚", $82
	charmap "罩", $83
	charmap "擅", $84
	charmap "夜", $85
	charmap "晚", $86
	charmap "動", $87
	charmap "其", $88
	charmap "爪", $89
	charmap "將", $8a
	charmap "獵", $8b
	charmap "撕", $8c
	charmap "半", $8d
	charmap "寵", $8e
	charmap "老", $8f
	charmap "男", $90
	charmap "女", $91
	charmap "孩", $92
	charmap "閱", $93 ; ?
	charmap "櫃", $94
	charmap "阿", $95
	charmap "飽", $96
	charmap "四", $97
	charmap "五", $98
	charmap "六", $99
	charmap "七", $9a
	charmap "八", $9b
	charmap "白", $9c
	charmap "猦", $9d
	charmap "始", $9e
	charmap "繼", $9f
	charmap "續", $a0
	charmap "遊", $a1
	charmap "戲", $a2
	charmap "普", $a3
	charmap "辰", $a4
	charmap "虎", $a5
	charmap ":", $a6
	charmap "師", $a7
	charmap "兄", $a8
	charmap "較", $a9
	charmap "下", $aa
	charmap "吧", $ab
	charmap "嚴", $ac
	charmap "我", $ad
	charmap "輸", $ae
	charmap "給", $af
	charmap "試", $b0
	charmap "過", $b1
	charmap "才", $b2
	charmap "知", $b3
	charmap "麒", $b4
	charmap "麟", $b5
	charmap "上", $b6
	charmap "輪", $b7
	charmap "靠", $b8
	charmap "油", $b9
	charmap "厲", $ba
	charmap "害", $bb
	charmap "去", $bc
	charmap "做", $bd
	charmap "錯", $be
	charmap "來", $bf
	charmap "算", $c0
	charmap "危", $c1
	charmap "險", $c2
	charmap "招", $c3
	charmap "聚", $c4
	charmap "心", $c5
	charmap "躲", $c6
	charmap "⋯", $c7
	charmap "沒", $c8
	charmap "乎", $c9
	charmap "識", $ca
	charmap "起", $cb
	charmap "作", $cc
	charmap "好", $cd
	charmap "怎", $ce
	charmap "麼", $cf
	charmap "理", $d0
	charmap "想", $d1
	charmap "灼", $d2
	charmap "混", $d3
	charmap "嚇", $d4
	charmap "跳", $d5
	charmap "事", $d6
	charmap "就", $d7
	charmap "程", $d8
	charmap "勝", $d9
	charmap "再", $da
	charmap "努", $db
	charmap "得", $dc
	charmap "升", $dd
	charmap "揮", $de
	charmap "獲", $df

NEWCHARMAP charmap3
; 41:6000
	charmap "儲", $00
	charmap "底", $01
	charmap "植", $02
	charmap "豬", $03
	charmap "恢", $04
	charmap "燙", $05
	charmap "·", $06 ; interpunct
	charmap "送", $07
	charmap "託", $08
	charmap "管", $09
	charmap "盒", $0a
	charmap "現", $0b
	charmap "需", $0c
	charmap "什", $0d
	charmap "總", $0e
	charmap "共", $0f
	charmap "千", $10
	charmap "圓", $11
	charmap "春", $12
	charmap "躁", $13
	charmap "猴", $14
	charmap "綠", $15
	charmap "蛙", $16
	charmap "橡", $17
	charmap "皮", $18
	charmap "金", $19
	charmap "剛", $1a
	charmap "青", $1b
	charmap "笑", $1c
	charmap "爺", $1d
	charmap "長", $1e
	charmap "毛", $1f
	charmap "鳳", $20
	charmap "凰", $21
	charmap "赤", $22
	charmap "鍊", $23
	charmap "熔", $24
	charmap "岩", $25
	charmap "狐", $26
	charmap "燭", $27
	charmap "妖", $28
	charmap "焱", $29
	charmap "爐", $2a
	charmap "日", $2b
	charmap "河", $2c
	charmap "童", $2d
	charmap "錘", $2e
	charmap "翻", $2f
	charmap "江", $30
	charmap "鯉", $31
	charmap "夾", $32
	charmap "面", $33
	charmap "王", $34
	charmap "食", $35
	charmap "鯊", $36
	charmap "瓶", $37
	charmap "座", $38
	charmap "叢", $39
	charmap "蘑", $3a
	charmap "菇", $3b
	charmap "群", $3c
	charmap "足", $3d
	charmap "鐮", $3e
	charmap "蛇", $3f
	charmap "菊", $40
	charmap "蟲", $41
	charmap "蝴", $42
	charmap "蝶", $43
	charmap "獨", $44
	charmap "腳", $45
	charmap "鳩", $46
	charmap "蝠", $47
	charmap "塵", $48
	charmap "嘴", $49
	charmap "牛", $4a
	charmap "械", $4b
	charmap "蝙", $4c
	charmap "首", $4d
	charmap "泥", $4e
	charmap "蛟", $4f
	charmap "屍", $50
	charmap "閻", $51 ; ?
	charmap "傑", $52
	charmap "森", $53
	charmap "煞", $54
	charmap "寡", $55 ; ?
	charmap "婦", $56
	charmap "史", $57
	charmap "萊", $58
	charmap "姆", $59
	charmap "仙", $5a
	charmap "菩", $5b
	charmap "薩", $5c
	charmap "狗", $5d
	charmap "兵", $5e
	charmap "藍", $5f
	charmap "犬", $60
	charmap "貓", $61
	charmap "妙", $62
	charmap "維", $63
	charmap "京", $64
	charmap "鸚", $65
	charmap "鵡", $66
	charmap "熊", $67
	charmap "章", $68
	charmap "蟹", $69
	charmap "龜", $6a
	charmap "咕", $6b
	charmap "嚕", $6c
	charmap "蚌", $6d
	charmap "殼", $6e
	charmap "綿", $6f
	charmap "羊", $70
	charmap "螞", $71
	charmap "蟻", $72
	charmap "泰", $73
	charmap "山", $74
	charmap "絨", $75
	charmap "怯", $76
	charmap "膽", $77
	charmap "茸", $78
	charmap "馬", $79
	charmap "举", $7a ; ?
	charmap "插", $7b
	charmap "兔", $7c
	charmap "彩", $7d
	charmap "繪", $7e
	charmap "家", $7f
	charmap "咖", $80
	charmap "啡", $81
	charmap "滾", $82
	charmap "糢", $83
	charmap "困", $84
	charmap "途", $85
	charmap "玲", $86
	charmap "瓏", $87
	charmap "銷", $88
	charmap "閣", $89 ; ?
	charmap "勾", $8a
	charmap "乃", $8b
	charmap "伊", $8c
	charmap "蛋", $8d
	charmap "布", $8e
	charmap "蠍", $8f
	charmap "鏈", $90
	charmap "鼠", $91
	charmap "鬼", $92
	charmap "樂", $93
	charmap "郎", $94
	charmap "行", $95
	charmap "秘", $96
	charmap "徽", $97
	charmap "罰", $98
	charmap "雲", $99 ; ?
	charmap "在", $9a
	charmap "裡", $9b
	charmap "前", $9c
	charmap "候", $9d
	charmap "調", $9e
	charmap "味", $9f
	charmap "料", $a0
	charmap "媽", $a1
	charmap "妳", $a2
	charmap "答", $a3
	charmap "堅", $a4
	charmap "爸", $a5
	charmap "飯", $a6
	charmap "又", $a7
	charmap "文", $a8
	charmap "台", $a9
	charmap "陣", $aa
	charmap "整", $ab
	charmap "都", $ac
	charmap "待", $ad
	charmap "然", $ae
	charmap "辛", $af
	charmap "菜", $b0
	charmap "汪", $b1
	charmap "乖", $b2
	charmap "肚", $b3
	charmap "餓", $b4
	charmap "們", $b5
	charmap "賽", $b6 ; ?
	charmap "亞", $b7
	charmap "和", $b8
	charmap "他", $b9
	charmap "聊", $ba
	charmap "月", $bb
	charmap "亮", $bc
	charmap "張", $bd
	charmap "兮", $be
	charmap "往", $bf
	charmap "啊", $c0
	charmap "孝", $c1
	charmap "順", $c2
	charmap "病", $c3
	charmap "逝", $c4
	charmap "喲", $c5
	charmap "件", $c6
	charmap "哈", $c7
	charmap "昨", $c8
	charmap "考", $c9
	charmap "嘻", $ca
	charmap "每", $cb
	charmap "次", $cc
	charmap "教", $cd
	charmap "餅", $ce
	charmap "乾", $cf
	charmap "峨", $d0 ; ?
	charmap "啦", $d1
	charmap "唉", $d2
	charmap "呀", $d3
	charmap "最", $d4
	charmap "近", $d5
	charmap "睛", $d6 ; ?
	charmap "聞", $d7 ; ?
	charmap "報", $d8
	charmap "導", $d9
	charmap "明", $da
	charmap "規", $db
	charmap "年", $dc
	charmap "輕", $dd
	charmap "曾", $de
	charmap "預", $df

NEWCHARMAP charmap4
; 42:4000
	charmap "但", $00
	charmap "誤", $01
	charmap "告", $02
	charmap "訴", $03
	charmap "婆", $04
	charmap "村", $05
	charmap "名", $06
	charmap "美", $07
	charmap "隼", $08
	charmap "網", $09
	charmap "問", $0a
	charmap "題", $0b
	charmap "場", $0c
	charmap "今", $0d
	charmap "朋", $0e
	charmap "友", $0f
	charmap "多", $10
	charmap "把", $11
	charmap "別", $12
	charmap "毯", $13
	charmap "弄", $14
	charmap "髒", $15
	charmap "嗚", $16
	charmap "芳", $17
	charmap "唷", $18
	charmap "留", $19
	charmap "棒", $1a
	charmap "界", $1b
	charmap "只", $1c
	charmap "脾", $1d
	charmap "古", $1e
	charmap "玩", $1f
	charmap "難", $20
	charmap "見", $21
	charmap "景", $22
	charmap "洛", $23
	charmap "受", $24
	charmap "如", $25
	charmap "話", $26
	charmap "進", $27
	charmap "α", $28
	charmap "妮", $29
	charmap "校", $2a
	charmap "門", $2b
	charmap "關", $2c
	charmap "喧", $2d ;?
	charmap "像", $2e
	charmap "樣", $2f
	charmap "仔", $30
	charmap "顏", $31
	charmap "色", $32
	charmap "暖", $33
	charmap "澄", $34
	charmap "黃", $35
	charmap "怕", $36
	charmap "終", $37
	charmap "早", $38
	charmap "槽", $39
	charmap "趕", $3a
	charmap "快", $3b
	charmap "歲", $3c
	charmap "期", $3d
	charmap "曉", $3e
	charmap "為", $3f
	charmap "露", $40
	charmap "臉", $41
	charmap "溜", $42
	charmap "噠", $43
	charmap "窒", $44
	charmap "課", $45
	charmap "情", $46
	charmap "表", $47
	charmap "吉", $48
	charmap "介", $49
	charmap "紹", $4a
	charmap "貴", $4b ; ?
	charmap "酸", $4c
	charmap "萄", $4d
	charmap "葡", $4e
	charmap "借", $4f
	charmap "誰", $50
	charmap "趣", $51
	charmap "莫", $52
	charmap "坐", $53
	charmap "右", $54
	charmap "兒", $55
	charmap "專", $56
	charmap "聽", $57
	charmap "壯", $58
	charmap "觀", $59
	charmap "豪", $5a
	charmap "望", $5b
	charmap "遠", $5c
	charmap "資", $5d ; ?
	charmap "弗", $5e
	charmap "茲", $5f
	charmap "系", $60
	charmap "距", $61
	charmap "獎", $62
	charmap "勵", $63
	charmap "父", $64
	charmap "親", $65
	charmap "商", $66
	charmap "館", $67
	charmap "讓", $68
	charmap "賞", $69
	charmap "壞", $6a
	charmap "諭", $6b
	charmap "住", $6c
	charmap "論", $6d
	charmap "聲", $6e
	charmap "某", $6f
	charmap "房", $70
	charmap "索", $71
	charmap "抽", $72
	charmap "罹", $73 ; ?
	charmap "容", $74
	charmap "寫", $75
	charmap "跡", $76
	charmap "臨", $77
	charmap "恐", $78
	charmap "泛", $79
	charmap "計", $7a
	charmap "畫", $7b
	charmap "構", $7c
	charmap "造", $7d
	charmap "雖", $7e
	charmap "願", $7f
	charmap "意", $80
	charmap "趟", $81
	charmap "按", $82
	charmap "鈕", $83
	charmap "減", $84
	charmap "少", $85
	charmap "塔", $86
	charmap "毀", $87
	charmap "些", $88
	charmap "稱", $89
	charmap "因", $8a
	charmap "係", $8b
	charmap "哇", $8c
	charmap "追", $8d
	charmap "縫", $8e
	charmap "鄖", $8f
	charmap "砸", $90
	charmap "牠", $91
	charmap "掉", $92
	charmap "糕", $93
	charmap "辦", $94
	charmap "衛", $95
	charmap "軍", $96
	charmap "團", $97
	charmap "咦", $98
	charmap "歐", $99
	charmap "博", $9a
	charmap "士", $9b
	charmap "隔", $9c
	charmap "城", $9d
	charmap "煩", $9e
	charmap "羞", $9f
	charmap "照", $a0
	charmap "顧", $a1
	charmap "孤", $a2
	charmap "蹤", $a3
	charmap "振", $a4
	; charmap "振", $a5 ; duplicate (hopefully never used)
	charmap "路", $a6
	charmap "捉", $a7
	charmap "邊", $a8
	charmap "歷", $a9
	charmap "研", $aa
	charmap "究", $ab
	charmap "拯", $ac
	charmap "跟", $ad
	charmap "約", $ae
	charmap "講", $af
	charmap "昏", $b0
	charmap "停", $b1
	charmap "連", $b2
	charmap "燈", $b3
	charmap "久", $b4
	charmap "故", $b5
	charmap "哎", $b6
	charmap "痛", $b7
	charmap "漆", $b8
	charmap "楚", $b9
	charmap "骨", $ba
	charmap "賭", $bb
	charmap "製", $bc
	charmap "污", $bd
	charmap "辱", $be
	charmap "慎", $bf
	charmap "派", $c0
	charmap "引", $c1
	charmap "敢", $c2
	charmap "信", $c3
	charmap "籌", $c4
	charmap "世", $c5
	charmap "市", $c6
	charmap "外", $c7
	charmap "虧", $c8
	charmap "祖", $c9
	charmap "敬", $ca
	charmap "卻", $cb
	charmap "誇", $cc
	charmap "估", $cd
	charmap "廢", $ce
	charmap "爛", $cf
	charmap "東", $d0
	charmap "西", $d1
	charmap "貝", $d2
	charmap "紀", $d3
	charmap "克", $d4
	charmap "覺", $d5
	charmap "憂", $d6 ; ?
	charmap "鬱", $d7
	charmap "驅", $d8
	charmap "形", $d9
	charmap "範", $da
	charmap "措", $db
	charmap "施", $dc
	charmap "代", $dd
	charmap "該", $de
	charmap "哼", $df

NEWCHARMAP charmap5
; 42:6000
	charmap "欺", $00
	charmap "負", $01
	charmap "幫", $02
	charmap "改", $03
	charmap "湊", $04
	charmap "荳", $05
	charmap "筋", $06
	charmap "修", $07
	charmap "初", $08
	charmap "價", $09
	charmap "億", $0a
	charmap "擔", $0b
	charmap "銀", $0c
	charmap "趁", $0d
	charmap "治", $0e
	charmap "艾", $0f
	charmap "娜", $10
	charmap "魯", $11
	charmap "爾", $12
	charmap "企", $13
	charmap "業", $14
	charmap "採", $15
	charmap "購", $16
	charmap "議", $17
	charmap "賠", $18
	charmap "譽", $19
	charmap "您", $1a
	charmap "甘", $1b
	charmap "竟", $1c
	charmap "指", $1d
	charmap "呵", $1e
	charmap "賴", $1f
	charmap "帳", $20
	charmap "傢", $21
	charmap "伙", $22
	charmap "承", $23
	charmap "諾", $24
	charmap "既", $25
	charmap "仁", $26
	charmap "慈", $27
	charmap "義", $28
	charmap "穿", $29
	charmap "梭", $2a
	charmap "浪", $2b
	charmap "漫", $2c
	charmap "勇", $2d
	charmap "貫", $2e
	charmap "徹", $2f
	charmap "愛", $30
	charmap "拉", $31
	charmap "琪", $32
	charmap "庫", $33
	charmap "誕", $34
	charmap "戒", $35
	charmap "『", $36
	charmap "磅", $37
	charmap "』", $38
	charmap "贏", $39
	charmap "認", $3a
	charmap "胡", $3b
	charmap "脆", $3c
	charmap "慘", $3d
	charmap "恰", $3e
	charmap "握", $3f
	charmap "零", $40
	charmap "虹", $41
	charmap "産", $42
	charmap "拿", $43
	charmap "礦", $44
	charmap "區", $45
	charmap "霸", $46
	charmap "佔", $47
	charmap "工", $48
	charmap "閉", $49
	charmap "雇", $4a
	charmap "搞", $4b
	charmap "櫥", $4c
	charmap "公", $4d
	charmap "豐", $4e
	charmap "盛", $4f
	charmap "午", $50
	charmap "煮", $51
	charmap "結", $52
	charmap "口", $53
	charmap "袋", $54
	charmap "顆", $55
	charmap "耶", $56
	charmap "站", $57
	charmap "盤", $58
	charmap "、", $59
	charmap "碼", $5a
	charmap "¢", $5b
	charmap "#", $5c
	charmap "×", $5d
	charmap "°", $5e
	charmap "£", $5f
	charmap "M", $60
	charmap "K", $61
	charmap "C", $62
	charmap "-", $63 ; (temp) log
	charmap "+", $64 ; (temp) ln
	charmap "訓", $65
	charmap "及", $66
	charmap "姐", $67
	charmap "退", $68
	charmap "擋", $69
	charmap "阻", $6a
	charmap "坑", $6b
	charmap "息", $6c
	charmap "頓", $6d
	charmap "陰", $6e
	charmap "影", $6f
	charmap "尾", $70
	charmap "展", $71
	charmap "慢", $72
	charmap "武", $73
	charmap "佩", $74
	charmap "智", $75
	charmap "慧", $76
	charmap "尊", $77
	charmap "第", $78
	charmap "察", $79
	charmap "喵", $7a
	charmap "z", $7b
	charmap "Z", $7c
	charmap "向", $7d
	charmap "注", $7e
	charmap "況", $7f
	charmap "條", $80
	charmap "直", $81
	charmap "恥", $82
	charmap "它", $83
	charmap "烏", $84
	charmap "嘛", $85
	charmap "堆", $86
	charmap "蒙", $87 ; ?
	charmap "喂", $88
	charmap "咪", $89
	charmap "(", $8a
	charmap ")", $8b
	charmap "权", $8c
	charmap "謝", $8d
	charmap "詢", $8e
	charmap "視", $8f
	charmap "育", $90
	charmap "恩", $91
	charmap "惠", $92
	charmap "幸", $93
	charmap "福", $94
	charmap "晴", $95
	charmap "易", $96
	charmap "慣", $97
	charmap "邦", $98
	charmap "林", $99
	charmap "登", $9a
	charmap "忙", $9b
	charmap "參", $9c
	charmap "越", $9d
	charmap "船", $9e
	charmap "唯", $9f
	charmap "標", $a0
	charmap "份", $a1
	charmap "或", $a2
	charmap "許", $a3
	charmap "由", $a4
	charmap "保", $a5
	charmap "責", $a6
	charmap "尋", $a7
	charmap "乘", $a8
	charmap "董", $a9
	charmap "令", $aa
	charmap "言", $ab
	charmap "各", $ac
	charmap "P", $ad
	charmap "D", $ae
	charmap "A", $af
	charmap "餘", $b0
	charmap "則", $b1
	charmap "彼", $b2
	charmap "畢", $b3
	charmap "式", $b4
	charmap "搭", $b5
	charmap "型", $b6
	charmap "凹", $b7
	charmap "&", $b8
	charmap "籍", $b9
	charmap "排", $ba
	charmap "床", $bb
	charmap "統", $bc
	charmap "語", $bd
	charmap "員", $be
	charmap "棟", $bf
	charmap "建", $c0
	charmap "築", $c1
	charmap "鼎", $c2
	charmap "示", $c3
	charmap "版", $c4
	charmap "憐", $c5
	charmap "十", $c6
	charmap "孫", $c7
	charmap "念", $c8
	charmap "依", $c9
	charmap "掛", $ca
	charmap "琉", $cb
	charmap "璃", $cc
	charmap "財", $cd
	charmap "筆", $ce
	charmap "搶", $cf
	charmap "遜", $d0
	charmap "與", $d1
	charmap "牧", $d2
	charmap "戀", $d3
	charmap "憤", $d4
	charmap "攀", $d5
	charmap "拆", $d6
	charmap "嬰", $d7
	charmap "南", $d8
	charmap "農", $d9
	charmap "莊", $da
	charmap "純", $db
	charmap "樸", $dc
	charmap "鎮", $dd ; ?
	charmap "龐", $de
	charmap "哥", $df

NEWCHARMAP charmap6
; 43:4000
	charmap "倍", $00
	charmap "寂", $01
	charmap "寞", $02
	charmap "鄰", $03
	charmap "填", $04
	charmap "平", $05
	charmap "托", $06
	charmap "遺", $07
	charmap "憾", $08
	charmap "操", $09
	charmap "勞", $0a
	charmap "休", $0b
	charmap "接", $0c
	charmap "客", $0d
	charmap "求", $0e
	charmap "節", $0f
	charmap "啟", $10
	charmap "戴", $11
	charmap "弦", $12
	charmap "幽", $13
	charmap "禮", $14
	charmap "尤", $15
	charmap "旁", $16
	charmap "鼻", $17
	charmap "捏", $18
	charmap "差", $19
	charmap "股", $1a
	charmap "蔓", $1b ; ?
	charmap "延", $1c
	charmap "窗", $1d
	charmap "妹", $1e
	charmap "肆", $1f
	charmap "鳴", $20
	charmap "街", $21
	charmap "彷", $22
	charmap "彿", $23
	charmap "豆", $24
	charmap "據", $25
	charmap "呃", $26
	charmap "咩", $27
	charmap "愈", $28 ; ?
	charmap "緻", $29
	charmap "吐", $2a
	charmap "倒", $2b
	charmap "慶", $2c
	charmap "祝", $2d
	charmap "決", $2e
	charmap "杯", $2f
	charmap "思", $30
	charmap "累", $31
	charmap "質", $32
	charmap "她", $33
	charmap "扮", $34
	charmap "采", $35 ; ?
	charmap "痕", $36
	charmap "X", $37
	charmap "季", $38
	charmap "胸", $39
	charmap "瞧", $3a
	charmap "泠", $3b
	charmap "賜", $3c
	charmap "予", $3d
	charmap "私", $3e
	charmap "禁", $3f
	charmap "劇", $40
	charmap "傻", $41
	charmap "喜", $42
	charmap "歡", $43
	charmap "端", $44
	charmap "儘", $45
	charmap "逼", $46
	charmap "恍", $47
	charmap "持", $48
	charmap "緣", $49
	charmap "字", $4a
	charmap "奈", $4b
	charmap "刻", $4c
	charmap "悲", $4d
	charmap "仍", $4e
	charmap "諒", $4f
	charmap "希", $50
	charmap "桑", $51
	charmap "絲", $52
	charmap "永", $53
	charmap "肯", $54
	charmap "塊", $55
	charmap "配", $56
	charmap "舉", $57
	charmap "典", $58
	charmap "賓", $59 ; ?
	charmap "廳", $5a
	charmap "艘", $5b
	charmap "朝", $5c
	charmap "適", $5d
	charmap "僕", $5e
	charmap "夫", $5f
	charmap "羨", $60 ; ?
	charmap "慕", $61
	charmap "佈", $62
	charmap "擺", $63
	charmap "怖", $64
	charmap "嘀", $65
	charmap "囉", $66
	charmap "昱", $67
	charmap "頻", $68
	charmap "紙", $69
	charmap "職", $6a
	charmap "裁", $6b
	charmap "偉", $6c
	charmap "瑪", $6d
	charmap "跨", $6e
	charmap "鑰", $6f
	charmap "匙", $70
	charmap "扇", $71
	charmap "贊", $72
	charmap "嗨", $73
	charmap "O", $74
	charmap "H", $75
	charmap "B", $76
	charmap "Y", $77
	charmap "N", $78
	charmap "樓", $79
	charmap "甄", $7a
	charmap "秀", $7b
	charmap "麗", $7c
	charmap "护", $7d ; ?
	charmap "堂", $7e
	charmap "漂", $7f
	charmap "噁", $80
	charmap "鑲", $81
	charmap "蜜", $82
	charmap "糖", $83
	charmap "簽", $84
	charmap "羔", $85
	charmap "姿", $86
	charmap "冠", $87
	charmap "附", $88
	charmap "德", $89
	charmap "頑", $8a
	charmap "珍", $8b
	charmap "珠", $8c
	charmap "侯", $8d
	charmap "練", $8e ; ?
	charmap "謊", $8f
	charmap "愉", $90
	charmap "至", $91
	charmap "檯", $92
	charmap "掀", $93
	charmap "罵", $94
	charmap "崁", $95
	charmap "襯", $96
	charmap "雅", $97
	charmap "供", $98
	charmap "階", $99
	charmap "段", $9a
	charmap "響", $9b
	charmap "訂", $9c
	charmap "售", $9d
	charmap "另", $9e
	charmap "慮", $9f
	charmap "編", $a0
	charmap "套", $a1
	charmap "穎", $a2
	charmap "飾", $a3
	charmap "店", $a4
	charmap "܅", $a5 ; (smol)
	charmap "卑", $a6
	charmap "鄙", $a7
	charmap "醜", $a8
	charmap "副", $a9
	charmap "蹦", $aa
	charmap "膩", $ab
	charmap "象", $ac
	charmap "踩", $ad
	charmap "拱", $ae
	charmap "嶼", $af
	charmap "溝", $b0
	charmap "偶", $b1
	charmap "旅", $b2
	charmap "撩", $b3
	charmap "牙", $b4
	charmap "轟", $b5
	charmap "隆", $b6
	charmap "陋", $b7
	charmap "優", $b8
	charmap "蘿", $b9
	charmap "蔔", $ba
	charmap "媲", $bb
	charmap "懂", $bc
	charmap "喔", $bd
	charmap "耳", $be
	charmap "朵", $bf
	charmap "評", $c0
	charmap "審", $c1
	charmap "窮", $c2
	charmap "疼", $c3
	charmap "根", $c4
	charmap "釘", $c5
	charmap "循", $c6
	charmap "環", $c7
	charmap "淘", $c8
	charmap "汰", $c9
	charmap "涵", $ca
	charmap "敏", $cb
	charmap "僵", $cc
	charmap "咭", $cd
	charmap "罷", $ce
	charmap "宣", $cf
	charmap "薇", $d0
	charmap "潮", $d1
	charmap "迎", $d2 ; ?
	charmap "悅", $d3
	charmap "夏", $d4
	charmap "娃", $d5
	charmap "勁", $d6
	charmap "簡", $d7
	charmap "創", $d8
	charmap "席", $d9
	charmap "頒", $da
	charmap "恭", $db
	charmap "傲", $dc
	charmap "胴", $dd
	charmap "欣", $de
	charmap "絞", $df

NEWCHARMAP charmap7
; 43:6000
	charmap "稍", $00
	charmap "微", $01
	charmap "饒", $02
	charmap "匆", $03
	charmap "淵", $04
	charmap "揭", $05
	charmap "鼓", $06
	charmap "觸", $07
	charmap "漁", $08
	charmap "跋", $09
	charmap "涉", $0a
	charmap "喝", $0b
	charmap "伯", $0c
	charmap "廁", $0d
	charmap "嘔", $0e
	charmap "哽", $0f
	charmap "卡", $10
	charmap "喉", $11
	charmap "嚨", $12
	charmap "舒", $13
	charmap "迪", $14
	charmap "鴿", $15
	charmap "胖", $16
	charmap "螃", $17
	charmap "蝦", $18
	charmap "巫", $19
	charmap "蒂", $1a
	charmap "港", $1b
	charmap "周", $1c
	charmap "耍", $1d
	charmap "棵", $1e
	charmap "洋", $1f
	charmap "未", $20
	charmap "婚", $21
	charmap "妻", $22
	charmap "惜", $23
	charmap "厚", $24
	charmap "島", $25
	charmap "轉", $26
	charmap "琳", $27
	charmap "訊", $28
	charmap "廣", $29
	charmap "郵", $2a
	charmap "李", $2b
	charmap "E", $2c
	charmap "I", $2d
	charmap "L", $2e
	charmap "掘", $2f
	charmap "繁", $30
	charmap "雜", $31
	charmap "瓜", $32
	charmap "游", $33
	charmap "咧", $34
	charmap "溺", $35 ; ?
	charmap "陸", $36
	charmap "討", $37
	charmap "厭", $38
	charmap "巡", $39
	charmap "域", $3a
	charmap "宜", $3b
	charmap "伸", $3c
	charmap "懇", $3d ; ?
	charmap "懷", $3e
	charmap "殿", $3f
	charmap "屏", $40
	charmap "瞞", $41
	charmap "劃", $42
	charmap "妄", $43
	charmap "甚", $44
	charmap "謂", $45
	charmap "沛", $46
	charmap "抵", $47
	charmap "呦", $48
	charmap "兇", $49
	charmap "奥", $4a
	charmap "仇", $4b
	charmap "騙", $4c
	charmap "喀", $4d
	charmap "償", $4e
	charmap "串", $4f
	charmap "探", $50
	charmap "湖", $51
	charmap "泊", $52
	charmap "沖", $53
	charmap "嫉", $54
	charmap "妒", $55
	charmap "x", $56
	charmap "谷", $57
	charmap "班", $58
	charmap "輩", $59 ; ?
	charmap "笛", $5a
	charmap "糊", $5b
	charmap "沿", $5c
	charmap "穩", $5d
	charmap "荒", $5e
	charmap "涼", $5f
	charmap "警", $60
	charmap "詭", $61
	charmap "番", $62
	charmap "吱", $63
	charmap "控", $64
	charmap "談", $65
	charmap "板", $66
	charmap "痴", $67
	charmap "狠", $68
	charmap "驕", $69
	charmap "廚", $6a
	charmap "$", $6b
	charmap "@", $6c
	charmap "※", $6d
	charmap "☆", $6e
	charmap "◇", $6f
	charmap "√", $70
	charmap "姨", $71
	charmap "疏", $72
	charmap "吹", $73
	charmap "奏", $74
	charmap "礙", $75
	charmap "漿", $76
	charmap "溢", $77
	charmap "嘿", $78
	charmap "爹", $79
	charmap "愧", $7a
	charmap "脅", $7b
	charmap "嘰", $7c
	charmap "盹", $7d
	charmap "推", $7e
	charmap "醉", $7f
	charmap "靜", $80
	charmap "拖", $81
	charmap "曠", $82
	charmap "扣", $83
	charmap "薪", $84
	charmap "炒", $85
	charmap "崇", $86
	charmap "喇", $87
	charmap "叽", $88
	charmap "英", $89
	charmap "雄", $8a
	charmap "屁", $8b
	charmap "嗶", $8c
	charmap "良", $8d
	charmap "泉", $8e
	charmap "酒", $8f
	charmap "圍", $90
	charmap "雕", $91
	charmap "抬", $92
	charmap "枯", $93
	charmap "遣", $94
	charmap "罪", $95
	charmap "冒", $96
	charmap "萎", $97
	charmap "組", $98
	charmap "織", $99
	charmap "抗", $9a
	charmap "勸", $9b
	charmap "善", $9c
	charmap "錶", $9d
	charmap "吊", $9e
	charmap "擴", $9f
	charmap "疑", $a0
	charmap "拜", $a1
	charmap "唸", $a2
	charmap "羅", $a3
	charmap "滑", $a4
	charmap "繩", $a5
	charmap "爬", $a6
	charmap "證", $a7
	charmap "溯", $a8
	charmap "革", $a9
	charmap "貼", $aa
	charmap "略", $ab
	charmap "熟", $ac
	charmap "悉", $ad
	charmap "挽", $ae
	charmap "齊", $af
	charmap "驟", $b0
	charmap "尚", $b1
	charmap "災", $b2
	charmap "滅", $b3
	charmap "榮", $b4
	charmap "帕", $b5
	charmap "母", $b6
	charmap "境", $b7
	charmap "燉", $b8
	charmap "鍋", $b9
	charmap "湯", $ba
	charmap "酬", $bb
	charmap "悔", $bc
	charmap "搜", $bd
	charmap "驚", $be
	charmap "帝", $bf
	charmap "佑", $c0
	charmap "懊", $c1
	charmap "惹", $c2
	charmap "闖", $c3 ; ?
	charmap "搗", $c4
	charmap "逆", $c5
	charmap "執", $c6
	charmap "互", $c7
	charmap "愚", $c8
	charmap "鑫", $c9 ; ?
	charmap "焚", $ca
	charmap "蓮", $cb
	charmap "睹", $cc
	charmap "族", $cd
	charmap "助", $ce
	charmap "吞", $cf
	charmap "噬", $d0
	charmap "狙", $d1
	charmap "晰", $d2
	charmap "胞", $d3
	charmap "軔", $d4 ; ?
	charmap "運", $d5
	charmap "碌", $d6
	charmap "幅", $d7
	charmap "列", $d8
	charmap "書", $d9
	charmap "積", $da
	charmap "遙", $db
	charmap "析", $dc
	charmap "授", $dd
	charmap "薦", $de
	charmap "F", $df

NEWCHARMAP charmap8
; 44:4000
	charmap "G", $00
	charmap "J", $01
	charmap "Q", $02
	charmap "R", $03
	charmap "S", $04
	charmap "T", $05
	charmap "U", $06
	charmap "V", $07
	charmap "W", $08
	charmap "擎", $09
	charmap "損", $0a
	charmap "暈", $0b ; ?
	charmap "絡", $0c
	charmap "航", $0d
	charmap "屋", $0e
	charmap "局", $0f
	charmap "潢", $10
	charmap "佳", $11
	charmap "洽", $12
	charmap "園", $13
	charmap "描", $14
	charmap "倆", $15
	charmap "劫", $16
	charmap "米", $17
	charmap "蘭", $18
	charmap "院", $19
	charmap "軌", $1a
	charmap "偏", $1b
	charmap "汐", $1c
	charmap "付", $1d
	charmap "藝", $1e
	charmap "肉", $1f
	charmap "症", $20
	charmap "架", $21
	charmap "鮮", $22
	charmap "栽", $23
	charmap "培", $24
	charmap "漢", $25
	charmap "慨", $26
	charmap "媞", $27 ; ?
	charmap "免", $28
	charmap "翹", $29
	charmap "診", $2a
	charmap "檢", $2b
	charmap "橋", $2c
	charmap "衰", $2d
	charmap "淡", $2e
	charmap "牽", $2f ; ?
	charmap "層", $30
	charmap "折", $31
	charmap "奄", $32
	charmap "緒", $33
	charmap "憶", $34
	charmap "激", $35
	charmap "帽", $36
	charmap "染", $37
	charmap "紫", $38
	charmap "宅", $39
	charmap "宁", $3a ; ?
	charmap "立", $3b
	charmap "隅", $3c
	charmap "粗", $3d
	charmap "肺", $3e
	charmap "皺", $3f
	charmap "紋", $40
	charmap "奶", $41
	charmap "猶", $42
	charmap "豫", $43
	charmap "假", $44
	charmap "棉", $45
	charmap "契", $46
	charmap "皇", $47
	charmap "倫", $48
	charmap "焕", $49 ; ?
	charmap "踏", $4a
	charmap "籟", $4b ; ?
	charmap "潑", $4c
	charmap "違", $4d
	charmap "背", $4e
	charmap "北", $4f
	charmap "敲", $50
	charmap "材", $51
	charmap "魄", $52
	charmap "支", $53
	charmap "赴", $54
	charmap "須", $55
	charmap "押", $56
	charmap "鍵", $57
	charmap "衡", $58
	charmap "旦", $59
	charmap "襲", $5a
	charmap "括", $5b
	charmap "菈", $5c ; ?
	charmap "忠", $5d
	charmap "鬍", $5e ; ?
	charmap "渣", $5f ; ?
	charmap "鋼", $60
	charmap "鋪", $61
	charmap "鑄", $62
	charmap "爽", $63
	charmap "際", $64
	charmap "擬", $65
	charmap "屆", $66
	charmap "浩", $67
	charmap "播", $68
	charmap "迫", $69
	charmap "末", $6a
	charmap "陪", $6b
	charmap "滋", $6c
	charmap "割", $6d
	charmap "择", $6e
	charmap "扎", $6f
	charmap "躍", $70
	charmap "墜", $71
	charmap "淨", $72
	charmap "宿", $73
	charmap "嚐", $74
	charmap "灰", $75
	charmap "馭", $76
	charmap "委", $77
	charmap "暫", $78
	charmap "竄", $79
	charmap "州", $7a
	charmap "掩", $7b
	charmap "彌", $7c
	charmap "泳", $7d
	charmap "唆", $7e
	charmap "召", $7f
	charmap "演", $80
	charmap "砲", $81
	charmap "臭", $82
	charmap "爭", $83
	charmap "呤", $84
	charmap "唱", $85
	charmap "炙", $86
	charmap "偑", $87
	charmap "奉", $88
	charmap "吾", $89
	charmap "囚", $8a
	charmap "汝", $8b
	charmap "蒸", $8c
	charmap "懼", $8d
	charmap "綻", $8e
	charmap "詞", $8f
	charmap "菌", $90
	charmap "咻", $91
	charmap "概", $92
	charmap "訝", $93
	charmap "瞭", $94
	charmap "瑕", $95
	charmap "卯", $96
	charmap "九", $97
	charmap "尺", $98
	charmap "寸", $99
	charmap "憨", $9a
	charmap "縱", $9b
	charmap "穴", $9c
	charmap "辨", $9d
	charmap "殘", $9e ; ?
	charmap "罕", $9f
	charmap "燄", $a0
	charmap "灘", $a1
	charmap "燃", $a2
	charmap "徵", $a3
	charmap "苗", $a4
	charmap "蠟", $a5
	charmap "丹", $a6
	charmap "溫", $a7
	charmap "渡", $a8
	charmap "豚", $a9
	charmap "弟", $aa
	charmap "薄", $ab
	charmap "透", $ac
	charmap "頰", $ad
	charmap "遭", $ae
	charmap "卵", $af
	charmap "川", $b0
	charmap "宙", $b1
	charmap "凡", $b2
	charmap "慾", $b3
	charmap "壤", $b4
	charmap "艷", $b5
	charmap "銳", $b6
	charmap "砍", $b7
	charmap "軀", $b8
	charmap "沼", $b9
	charmap "澤", $ba
	charmap "飘", $bb ; ?
	charmap "判", $bc
	charmap "僅", $bd
	charmap "搬", $be
	charmap "翔", $bf
	charmap "稀", $c0
	charmap "螺", $c1
	charmap "鏽", $c2
	charmap "遮", $c3
	charmap "蔽", $c4
	charmap "阱", $c5
	charmap "淆", $c6
	charmap "臂", $c7
	charmap "腕", $c8
	charmap "癢", $c9
	charmap "旺", $ca
	charmap "趾", $cb ; ?
	charmap "額", $cc
	charmap "劈", $cd
	charmap "斧", $ce
	charmap "齒", $cf
	charmap "歹", $d0
	charmap "淒", $d1
	charmap "繞", $d2
	charmap "垃", $d3
	charmap "圾", $d4
	charmap "赦", $d5
	charmap "咳", $d6
	charmap "拐", $d7
	charmap "杖", $d8
	charmap "兆", $d9
	charmap "凝", $da
	charmap "誌", $db
	charmap "藉", $dc
	charmap "捨", $dd
	charmap "貌", $de
	charmap "誠", $df

NEWCHARMAP charmap9
; 44:6000
	charmap "讚", $00
	charmap "揚", $01
	charmap "濕", $02
	charmap "殆", $03
	charmap "熾", $04
	charmap "吒", $05
	charmap "窺", $06
	charmap "覓", $07 ; ?
	charmap "冬", $08
	charmap "腹", $09
	charmap "膚", $0a
	charmap "里", $0b
	charmap "剔", $0c ; ?
	charmap "韌", $0d
	charmap "志", $0e
	charmap "桀", $0f
	charmap "桀", $10
	charmap "髮", $11
	charmap "肌", $12
	charmap "豎", $13
	charmap "盲", $14
	charmap "彎", $15
	charmap "曲", $16
	charmap "伞", $17 ; ?
	charmap "峽", $18
	charmap "溪", $19
	charmap "摧", $1a
	charmap "享", $1b
	charmap "央", $1c
	charmap "陀", $1d
	charmap "抛", $1e
	charmap "捕", $1f
	charmap "聰", $20
	charmap "裹", $21
	charmap "衍", $22
	charmap "室", $23 ; ?
	charmap "隧", $24
	charmap "歌", $25
	charmap "搉", $26
	charmap "邀", $27
	charmap "姬", $28
	charmap "箱", $29
	charmap "廠", $2a
	charmap "↑", $2b
	charmap "↓", $2c
	charmap "←", $2d
	charmap "→", $2e
	charmap "↖", $2f
	charmap "↗", $30
	charmap "↙", $31
	charmap "↘", $32
	charmap "閒", $33 ; ?
	charmap "勿", $34
	charmap "区", $35
	charmap "拘", $36
	charmap "莽", $37
	charmap "富", $38
	charmap "炫", $39
	charmap "耀", $3a
	charmap "酷", $3b
	charmap "缺", $3c
	charmap "乏", $3d
	charmap "隕", $3e
	charmap "遵", $3f
