NEWCHARMAP charmap0
; 40:4000
	charmap " ", $00
	charmap "死", $01
	charmap "之", $02
	charmap "吻", $03
	charmap "狂", $04
	charmap "咬", $05
	charmap "打", $06
	charmap "擊", $07
	charmap "瘋", $08
	charmap "突", $09
	charmap "防", $0a
	charmap "禦", $0b
	charmap "破", $0c
	charmap "碎", $0d
	charmap "催", $0e
	charmap "眠", $0f
	charmap "術", $10
	charmap "煙", $11
	charmap "幕", $12
	charmap "彈", $13
	charmap "百", $14
	charmap "裂", $15
	charmap "巴", $16
	charmap "掌", $17
	charmap "全", $18
	charmap "力", $19
	charmap "一", $1a
	charmap "集", $1b
	charmap "氣", $1c
	charmap "硬", $1d
	charmap "化", $1e
	charmap "封", $1f
	charmap "印", $20
	charmap "忍", $21
	charmap "耐", $22
	charmap "人", $23
	charmap "攻", $24
	charmap "細", $25
	charmap "綁", $26
	charmap "精", $27
	charmap "神", $28
	charmap "中", $29
	charmap "療", $2a
	charmap "傷", $2b
	charmap "尖", $2c
	charmap "叫", $2d
	charmap "犧", $2e
	charmap "牲", $2f
	charmap "勒", $30
	charmap "緊", $31
	charmap "不", $32
	charmap "放", $33
	charmap "電", $34
	charmap "光", $35
	charmap "閃", $36
	charmap "分", $37
	charmap "身", $38
	charmap "熱", $39
	charmap "血", $3a
	charmap "正", $3b
	charmap "拳", $3c
	charmap "石", $3d
	charmap "縮", $3e
	charmap "小", $3f
	charmap "槍", $40
	charmap "刺", $41
	charmap "洗", $42
	charmap "腦", $43
	charmap "拍", $44
	charmap "翅", $45
	charmap "膀", $46
	charmap "偷", $47
	charmap "吃", $48
	charmap "步", $49
	charmap "先", $4a
	charmap "發", $4b
	charmap "制", $4c
	charmap "角", $4d
	charmap "致", $4e
	charmap "命", $4f
	charmap "殺", $50
	charmap "狼", $51
	charmap "嚎", $52
	charmap "潛", $53
	charmap "哀", $54
	charmap "號", $55
	charmap "沉", $56 ; ?
	charmap "睡", $57
	charmap "疾", $58
	charmap "風", $59
	charmap "護", $5a
	charmap "銅", $5b
	charmap "牆", $5c
	charmap "鐵", $5d
	charmap "壁", $5e
	charmap "瞄", $5f
	charmap "準", $60
	charmap "劍", $61
	charmap "切", $62
	charmap "斬", $63
	charmap "撞", $64
	charmap "刀", $65
	charmap "兩", $66
	charmap "斷", $67
	charmap "靈", $68
	charmap "二", $69
	charmap "流", $6a
	charmap "盾", $6b
	charmap "勢", $6c
	charmap "瞬", $6d
	charmap "間", $6e
	charmap "手", $6f
	charmap "居", $70
	charmap "合", $71
	charmap "蓄", $72
	charmap "鬥", $73
	charmap "·", $74
	charmap "嵐", $75
	charmap "無", $76
	charmap "雙", $77
	charmap "噸", $78
	charmap "摔", $79
	charmap "地", $7a
	charmap "獄", $7b
	charmap "車", $7c
	charmap "必", $7d
	charmap "投", $7e
	charmap "擲", $7f
	charmap "天", $80
	charmap "寒", $81
	charmap "冰", $82
	charmap "烈", $83
	charmap "焰", $84
	charmap "吸", $85
	charmap "收", $86
	charmap "反", $87
	charmap "亂", $88 ; ?
	charmap "通", $89
	charmap "火", $8a
	charmap "炎", $8b
	charmap "噴", $8c
	charmap "射", $8d
	charmap "旋", $8e
	charmap "爆", $8f
	charmap "炸", $90
	charmap "鳥", $91
	charmap "翼", $92
	charmap "同", $93
	charmap "歸", $94
	charmap "於", $95
	charmap "盡", $96
	charmap "毒", $97
	charmap "濃", $98
	charmap "泡", $99
	charmap "沫", $9a
	charmap "雨", $9b
	charmap "飄", $9c
	charmap "紅", $9d
	charmap "強", $9e
	charmap "水", $9f
	charmap "柱", $a0
	charmap "暴", $a1
	charmap "海", $a2
	charmap "嘯", $a3
	charmap "凍", $a4
	charmap "束", $a5
	charmap "雪", $a6
	charmap "黑", $a7
	charmap "暗", $a8
	charmap "飛", $a9
	charmap "砂", $aa
	charmap "走", $ab
	charmap "落", $ac
	charmap "崩", $ad
	charmap "挖", $ae
	charmap "洞", $af
	charmap "大", $b0
	charmap "震", $b1
	charmap "殞", $b2
	charmap "巨", $b3
	charmap "雷", $b4
	charmap "閣", $b5 ; ?
	charmap "延", $b6 ; ?
	charmap "頂", $b7
	charmap "磁", $b8
	charmap "波", $b9
	charmap "星", $ba
	charmap "法", $bb
	charmap "藤", $bc
	charmap "鞭", $bd
	charmap "樹", $be
	charmap "汁", $bf ; ?
	charmap "散", $c0
	charmap "葉", $c1
	charmap "片", $c2
	charmap "太", $c3
	charmap "陽", $c4
	charmap "花", $c5
	charmap "寄", $c6
	charmap "魂", $c7
	charmap "種", $c8
	charmap "子", $c9
	charmap "香", $ca
	charmap "甜", $cb
	charmap "孢", $cc
	charmap "麻", $cd ; ?
	charmap "痺", $ce
	charmap "粉", $cf
	charmap "猛", $d0
	charmap "舌", $d1
	charmap "頭", $d2
	charmap "舔", $d3
	charmap "怨", $d4
	charmap "恨", $d5
	charmap "衝", $d6
	charmap "邪", $d7
	charmap "惡", $d8
	charmap "侵", $d9
	charmap "蝕", $da
	charmap "維", $db ; ?
	charmap "音", $dc
	charmap "魅", $dd
	charmap "惑", $de
	charmap "干", $df

NEWCHARMAP charmap1
; 40:6000
	charmap "擾", $00
	charmap "詛", $01
	charmap "咒", $02
	charmap "真", $03
	charmap "空", $04 ; ?
	charmap "過", $05
	charmap "龍", $06
	charmap "捲", $07 ; ?
	charmap "沙", $08
	charmap "漠", $09
	charmap "燕", $0a
	charmap "舞", $0b
	charmap "替", $0c
	charmap "弓", $0d
	charmap "念", $0e ; ?
	charmap "怒", $0f
	charmap "國", $10
	charmap "黏", $11
	charmap "液", $12
	charmap "模", $13
	charmap "仿", $14
	charmap "霧", $15 ; ?
	charmap "瓦", $16
	charmap "斯", $17
	charmap "淬", $18
	charmap "回", $19
	charmap "復", $1a
	charmap "獸", $1b
	charmap "竊", $1c
	charmap "變", $1d
	charmap "遁", $1e ; ?
	charmap "鏡", $1f
	charmap "謎", $20
	charmap "浴", $21
	charmap "重", $22
	charmap "生", $23
	charmap "華", $24
	charmap "三", $25
	charmap "味", $26
	charmap "障", $27
	charmap "主", $28
	charmap "怪", $29
	charmap "1", $2a
	charmap "2", $2b
	charmap "道", $2c ; ?
	charmap "具", $2d
	charmap "交", $2e
	charmap "換", $2f
	charmap "逃", $30
	charmap "跑", $31
	charmap "嗯", $32
	charmap ",", $33
	charmap "找", $34
	charmap "!", $35
	charmap "伴", $36
	charmap "圖", $37
	charmap "鑑", $38
	charmap "存", $39
	charmap "檔", $3a
	charmap "移", $3b
	charmap "位", $3c
	charmap "詳", $3d
	charmap "細", $3e
	charmap "使", $3f
	charmap "用", $40
	charmap "丟", $41
	charmap "棄", $42
	charmap "是", $43
	charmap "否", $44
	charmap "裝", $45
	charmap "備", $46
	charmap "確", $47
	charmap "定", $48
	charmap "取", $49
	charmap "消", $4a
	charmap "木", $4b
	charmap "格", $4c
	charmap "般", $4d
	charmap "請", $4e
	charmap "選", $4f
	charmap "擇", $50
	charmap "的", $51
	charmap "類", $52
	charmap "。", $53
	charmap "技", $54
	charmap "巧", $55
	charmap "已", $56
	charmap "滿", $57
	charmap "要", $58
	charmap "忘", $59
	charmap "記", $5a
	charmap "舊", $5b ; ?
	charmap "嗎", $5c
	charmap "?", $5d
	charmap "哪", $5e
	charmap "項", $5f
	charmap "學", $60
	charmap "習", $61
	charmap "到", $62
	charmap "新", $63
	charmap "了", $64
	charmap "有", $65
	charmap "案", $66
	charmap "錄", $67
	charmap "覆", $68
	charmap "蓋", $69
	charmap "成", $6a
	charmap "功", $6b
	charmap "失", $6c
	charmap "敗", $6d
	charmap "土", $6e
	charmap "草", $6f
	charmap "速", $70
	charmap "度", $71
	charmap "魔", $72
	charmap "經", $73
	charmap "驗", $74
	charmap "值", $75
	charmap "膠", $76
	charmap "票", $77 ; ?
	charmap "極", $78
	charmap "品", $79
	charmap "利", $7a
	charmap "果", $7b
	charmap "實", $7c
	charmap "醫", $7d
	charmap "包", $7e
	charmap "效", $7f
	charmap "蔡", $80
	charmap "超", $81
	charmap "健", $82
	charmap "康", $83
	charmap "針", $84
	charmap "齊", $85 ; ?
	charmap "解", $86
	charmap "清", $87
	charmap "興", $88
	charmap "奮", $89
	charmap "除", $8a
	charmap "青", $8b
	charmap "萬", $8c
	charmap "能", $8d
	charmap "急", $8e
	charmap "救", $8f
	charmap "機", $90
	charmap "器", $91
	charmap "甦", $92
	charmap "儀", $93
	charmap "壽", $94
	charmap "司", $95
	charmap "源", $96
	charmap "補", $97
	charmap "充", $98
	charmap "營", $99
	charmap "養", $9a
	charmap "餐", $9b
	charmap "迴", $9c
	charmap "避", $9d
	charmap "高", $9e
	charmap "軟", $9f
	charmap "呆", $a0
	charmap "滞", $a1
	charmap "眼", $a2
	charmap "遲", $a3
	charmap "緩", $a4
	charmap "隱", $a5 ; ?
	charmap "設", $a6
	charmap "達", $a7
	charmap "奇", $a8
	charmap "線", $a9
	charmap "晶", $aa
	charmap "3", $ab
	charmap "4", $ac
	charmap "5", $ad
	charmap "6", $ae
	charmap "7", $af
	charmap "8", $b0
	charmap "9", $b1
	charmap "0", $b2
	charmap "蹟", $b3
	charmap "元", $b4
	charmap "點", $b5
	charmap "滴", $b6
	charmap "魚", $b7
	charmap "整", $b8 ; ?
	charmap "整", $b9 ; ?
	charmap "娘", $ba
	charmap "麟", $bb ; ?
	charmap "淚", $bc
	charmap "淚", $bd
	charmap "甲", $be
	charmap "羽", $bf
	charmap "衣", $c0
	charmap "鬧", $c1
	charmap "鐘", $c2
	charmap "守", $c3
	charmap "玉", $c4
	charmap "幻", $c5
	charmap "特", $c6
	charmap "殊", $c7
	charmap "可", $c8
	charmap "服", $c9
	charmap "科", $ca
	charmap "以", $cb
	charmap "很", $cc
	charmap "率", $cd
	charmap "體", $ce
	charmap "方", $cf
	charmap "便", $d0
	charmap "隨", $d1
	charmap "而", $d2
	charmap "所", $d3
	charmap "提", $d4
	charmap "煉", $d5
	charmap "%", $d6
	charmap "內", $d7
	charmap "含", $d8
	charmap "傳", $d9
	charmap "說", $da
	charmap "狀", $db
	charmap "態", $dc
	charmap "燒", $dd
	charmap "涷", $de
	charmap "活", $df

NEWCHARMAP charmap2
; 41:4000
	charmap "並", $00
	charmap "單", $01
	charmap "數", $02
	charmap "戰", $03
	charmap "昇", $04
	charmap "降", $05
	charmap "低", $06
	charmap "對", $07
	charmap "從", $08
	charmap "脫", $09
	charmap "出", $0a
	charmap "開", $0b
	charmap "前", $0c ; ?
	charmap "物", $0d
	charmap "偵", $0e
	charmap "測", $0f
	charmap "置", $10
	charmap "絕", $11
	charmap "相", $12
	charmap "當", $13
	charmap "菩", $14
	charmap "澀", $15
	charmap "等", $16
	charmap "級", $17
	charmap "離", $18
	charmap "迷", $19
	charmap "宮", $1a
	charmap "載", $1b
	charmap "著", $1c
	charmap "视", $1d
	charmap "密", $1e
	charmap "~", $1f
	charmap "沈", $20
	charmap "後", $21
	charmap "即", $22
	charmap "亡", $23
	charmap "也", $24
	charmap "似", $25
	charmap "蘊", $26
	charmap "藏", $27
	charmap "还", $28 ; ?
	charmap "漸", $29
	charmap "增", $2a ; ?
	charmap "加", $2b
	charmap "屬", $2c
	charmap "性", $2d
	charmap "威", $2e
	charmap "陷", $2f
	charmap "入", $30
	charmap "深", $31
	charmap "時", $32
	charmap "會", $33
	charmap "噪", $34
	charmap "吵", $35
	charmap "醒", $36
	charmap "擁", $37
	charmap "者", $38
	charmap "帶", $39
	charmap "諸", $3a
	charmap "符", $3b
	charmap "止", $3c
	charmap "任", $3d
	charmap "何", $3e
	charmap "異", $3f
	charmap "常", $40
	charmap "夢", $41
	charmap "聖", $42
	charmap "潔", $43
	charmap "量", $44
	charmap "此", $45
	charmap "處", $46
	charmap "原", $47
	charmap "那", $48
	charmap "完", $49
	charmap "你", $4a
	charmap "錢", $4b
	charmap "夠", $4c
	charmap "買", $4d
	charmap "幾", $4e
	charmap "個", $4f
	charmap "呢", $50
	charmap "賣", $51
	charmap "務", $52
	charmap "目", $53
	charmap "欲", $54
	charmap "查", $55
	charmap "看", $56
	charmap "這", $57
	charmap "隻", $58
	charmap "抱", $59
	charmap "歉", $5a
	charmap "領", $5b
	charmap "隊", $5c
	charmap "伍", $5d
	charmap "更", $5e
	charmap "釋", $5f
	charmap "被", $60
	charmap "基", $61
	charmap "本", $62
	charmap "比", $63
	charmap "安", $64
	charmap "還", $65
	charmap "%", $66
	charmap "且", $67
	charmap "部", $68
	charmap "非", $69
	charmap "遇", $6a
	charmap "自", $6b
	charmap "己", $6c
	charmap "弱", $6d
	charmap "碰", $6e
	charmap "釣", $6f

	charmap "餌", $70
	charmap "感", $71
	charmap "應", $72
	charmap "寶", $73
	charmap "槌", $74
	charmap "獅", $75
	charmap "吼", $76
	charmap "蜜", $77 ; ?
	charmap "錯", $78
	charmap "孔", $79
	charmap "剝", $7a
	charmap "奪", $7b
	charmap "冷", $7c
	charmap "球", $7d
	charmap "刃", $7e
	charmap "茅", $7f
	charmap "核", $80
	charmap "呼", $81
	charmap "喚", $82
	charmap "罩", $83
	charmap "擅", $84
	charmap "夜", $85
	charmap "晚", $86
	charmap "動", $87
	charmap "其", $88
	charmap "爪", $89
	charmap "將", $8a
	charmap "獵", $8b
	charmap "斯", $8c ; ?
	charmap "半", $8d
	charmap "寵", $8e
	charmap "老", $8f
	charmap "男", $90
	charmap "女", $91
	charmap "孩", $92
	charmap "閱", $93 ; ?
	charmap "櫃", $94
	charmap "阿", $95
	charmap "飽", $96
	charmap "四", $97
	charmap "五", $98
	charmap "六", $99
	charmap "七", $9a
	charmap "八", $9b
	charmap "白", $9c
	charmap "狐", $9d ; ?
	charmap "始", $9e
	charmap "繼", $9f
	charmap "續", $a0
	charmap "遊", $a1
	charmap "戲", $a2
	charmap "普", $a3
	charmap "辰", $a4
	charmap "虎", $a5
	charmap ":", $a6
	charmap "師", $a7
	charmap "兄", $a8
	charmap "較", $a9
	charmap "下", $aa
	charmap "吧", $ab
	charmap "嚴", $ac
	charmap "我", $ad
	charmap "輸", $ae
	charmap "給", $af
	charmap "試", $b0
	charmap "過", $b1
	charmap "才", $b2
	charmap "知", $b3
	charmap "麒", $b4
	charmap "麟", $b5
	charmap "上", $b6
	charmap "輪", $b7
	charmap "靠", $b8
	charmap "油", $b9
	charmap "厲", $ba
	charmap "害", $bb
	charmap "去", $bc
	charmap "做", $bd
	charmap "錯", $be
	charmap "來", $bf
	charmap "算", $c0
	charmap "危", $c1
	charmap "險", $c2
	charmap "招", $c3
	charmap "聚", $c4
	charmap "心", $c5
	charmap "躲", $c6
	charmap "⋯", $c7
	charmap "沒", $c8
	charmap "乎", $c9
	charmap "識", $ca
	charmap "起", $cb
	charmap "作", $cc
	charmap "好", $cd
	charmap "怎", $ce
	charmap "麼", $cf
	charmap "理", $d0
	charmap "想", $d1
	charmap "灼", $d2
	charmap "混", $d3
	charmap "嚇", $d4
	charmap "跳", $d5
	charmap "事", $d6
	charmap "就", $d7
	charmap "程", $d8
	charmap "勝", $d9
	charmap "再", $da
	charmap "努", $db
	charmap "得", $dc
	charmap "升", $dd
	charmap "揮", $de
	charmap "獲", $df

NEWCHARMAP charmap3
; 41:6000

NEWCHARMAP charmap4
; 42:4000
	charmap "洛", $23

NEWCHARMAP charmap5
; 42:6000

NEWCHARMAP charmap6
; 43:4000

NEWCHARMAP charmap7
; 43:6000

NEWCHARMAP charmap8
; 44:4000

NEWCHARMAP charmap9
; 44:6000
